sudo: required
services:
  - docker
before_install:
  - docker build -t stevensymons/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stevensymons/react-test npm run test

after_success:
  - docker build -t stevensymons/multi-client ./client
  - docker build -t stevensymons/multi-nginx ./nginx
  - docker build -t stevensymons/multi-server ./server
  - docker build -t stevensymons/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stevensymons/multi-client
  - docker push stevensymons/multi-nginx
  - docker push stevensymons/multi-server
  - docker push stevensymons/multi-worker
